# Licensed under the Apache License, Version 2.0

import os
from pathlib import Path

from colcon_core.environment import create_environment_hooks, create_environment_scripts
from colcon_core.logging import colcon_logger
from colcon_core.plugin_system import satisfies_version
from colcon_core.shell import create_environment_hook
from colcon_core.task import TaskExtensionPoint, run

# Import Rust library directly via PyO3 bindings
from colcon_cargo_ros2 import cargo_ros2_py

logger = colcon_logger.getChild(__name__)


class AmentCargoBuildTask(TaskExtensionPoint):
    """A build task for Rust ROS 2 packages.

    Each package is built with a plain `cargo build` and installed into the
    ament layout. Message types are expected to be generated by the crates
    themselves (e.g. via a build script), so no rosidl bindings or
    `.cargo/config.toml` patches/rustflags are generated here.
    """

    def __init__(self):  # noqa: D107
        super().__init__()
        satisfies_version(TaskExtensionPoint.EXTENSION_POINT_VERSION, "^1.0")
        self._build_base = None  # Resolved in build() and used by install

    def add_arguments(self, *, parser):  # noqa: D102
        parser.add_argument(
            "--cargo-args",
            nargs="*",
            metavar="*",
            type=str.lstrip,
            help="Pass arguments to Cargo. "
            "Arguments matching other options must be prefixed by a space,\n"
            'e.g. --cargo-args " --help"',
        )

    async def build(self, *, additional_hooks=None):  # noqa: D102
        """Build the Rust ROS 2 package with cargo and install it to ament."""
        additional_hooks = [] if additional_hooks is None else additional_hooks

        # Step 1: Verify the native helper is available and resolve paths
        rc = self._prepare_build()
        if rc:
            return rc

        # Step 2: Create environment hooks and scripts
        await self._create_environment_scripts(additional_hooks)

        # Step 3: Build this package with cargo
        args = self.context.args
        cmd = self._build_cmd(args.cargo_args if hasattr(args, "cargo_args") else [])

        # Execute cargo build from the package source directory.
        pkg_dir = str(Path(self.context.pkg.path).resolve())
        result = await run(self.context, cmd, cwd=pkg_dir, env=None)
        if result and result.returncode != 0:
            return result.returncode

        # Step 4: Install binaries and create package markers
        rc = self._install_package()
        if rc:
            return rc

        # Return the exit code
        return 0

    def _prepare_build(self):
        """Verify the cargo_ros2 helper is available and resolve the build base."""
        # Check that cargo_ros2_py module is available (used by install)
        try:
            _ = cargo_ros2_py.__version__
            logger.debug(f"cargo_ros2_py {cargo_ros2_py.__version__} loaded")
        except (ImportError, AttributeError) as e:
            logger.error(
                f"\n\ncargo_ros2_py Rust bindings not found: {e}"
                "\n\nPlease ensure colcon-cargo-ros2 is installed correctly:"
                "\n  $ pip install colcon-cargo-ros2\n"
            )
            return 1

        # Workspace build/ directory, used when installing to ament.
        args = self.context.args
        self._build_base = Path(os.path.abspath(os.path.join(args.build_base, "..")))

        return 0

    async def _create_environment_scripts(self, additional_hooks):
        """Create environment hooks and scripts for ROS 2 integration.

        This creates:
        1. Individual hook scripts (e.g., ament_prefix_path.sh)
        2. Package scripts that source all hooks (package.sh, package.bash, etc.)
        3. Ensures ROS 2 compliance so CMake packages can find our packages
        """
        args = self.context.args
        pkg = self.context.pkg

        # Create additional hooks (e.g., ament_prefix_path)
        additional_hooks.extend(
            create_environment_hook(
                "ament_prefix_path",
                Path(args.install_base),
                pkg.name,
                "AMENT_PREFIX_PATH",
                "",
                mode="prepend",
            )
        )

        # Create default environment hooks (PATH, PYTHONPATH, etc.) from environment extensions
        default_hooks = create_environment_hooks(args.install_base, pkg.name)

        # Create package scripts (package.sh, package.bash, etc.) that source all hooks
        # This is what makes our Rust packages compatible with CMake packages
        create_environment_scripts(
            pkg, args, default_hooks=default_hooks, additional_hooks=additional_hooks
        )

    def _build_cmd(self, cargo_args):
        """Build the cargo build command.

        Uses --manifest-path to select the package being built.

        Adds --quiet flag by default to suppress cargo progress output (matching
        CMake/Python build behavior), unless verbose mode is enabled.
        """
        cmd = ["cargo", "build"]

        # Add --manifest-path to specify which package to build
        manifest_path = Path(self.context.pkg.path).resolve() / "Cargo.toml"
        cmd.extend(["--manifest-path", str(manifest_path)])

        # Handle None cargo_args
        if cargo_args is None:
            cargo_args = []

        # Add --quiet flag unless verbose mode is enabled or user explicitly passed --verbose
        # This suppresses "Compiling..." and "Finished..." messages but shows errors
        args = self.context.args
        verbose = getattr(args, "verbose", False)
        has_verbose_flag = "--verbose" in cargo_args or "-v" in cargo_args
        has_quiet_flag = "--quiet" in cargo_args or "-q" in cargo_args

        if not verbose and not has_verbose_flag and not has_quiet_flag:
            cmd.append("--quiet")

        # Add all cargo arguments
        cmd.extend(cargo_args)

        return cmd

    def _detect_cargo_profile(self, cargo_args, args):
        """Detect the cargo build profile from command-line arguments.

        Supports:
        - --release flag → "release"
        - --profile NAME → NAME (custom profile)
        - --profile=NAME → NAME (custom profile)
        - dev profile → "debug" (special case: dev outputs to target/debug/)
        - default → "debug"
        """
        # Check colcon-level --release flag first
        if hasattr(args, "release") and args.release:
            return "release"

        # Parse cargo arguments
        i = 0
        while i < len(cargo_args):
            arg = cargo_args[i]

            # Check for --release flag
            if arg == "--release":
                return "release"

            # Check for --profile=NAME syntax
            if arg.startswith("--profile="):
                profile_name = arg.split("=", 1)[1]
                # Special case: dev profile outputs to debug directory
                return "debug" if profile_name == "dev" else profile_name

            # Check for --profile NAME syntax (two separate args)
            if arg == "--profile" and i + 1 < len(cargo_args):
                profile_name = cargo_args[i + 1]
                # Special case: dev profile outputs to debug directory
                return "debug" if profile_name == "dev" else profile_name

            i += 1

        # Default to debug (dev profile)
        return "debug"

    def _install_package(self):
        """Install package binaries and create ament markers using direct API call."""
        args = self.context.args

        # Determine build profile from cargo arguments
        # Supports: --release, --profile NAME, --profile=NAME
        cargo_args = getattr(args, "cargo_args", []) or []
        profile = self._detect_cargo_profile(cargo_args, args)
        verbose = getattr(args, "verbose", False)

        # Execute installation via direct API call
        try:
            # Create configuration for installation
            # Ensure project_root is an absolute path
            project_root = Path(self.context.pkg.path).resolve()

            config = cargo_ros2_py.InstallConfig(
                project_root=str(project_root),
                install_base=str(args.install_base),
                build_base=str(self._build_base),
                profile=profile,
                verbose=verbose,
            )

            # Call Rust function directly (no subprocess!)
            cargo_ros2_py.install_to_ament(config)

            logger.info("✓ Package installed successfully")
            return 0

        except RuntimeError as e:
            logger.error(f"Installation failed: {e}")
            return 1
